// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {DummyRuleMap} from "oxlint"

const correctness: DummyRuleMap = {
  "eslint/constructor-super": "error",
  "eslint/for-direction": "error",
  "eslint/getter-return": "error",
  "eslint/no-async-promise-executor": "error",
  "eslint/no-caller": "error",
  "eslint/no-class-assign": "error",
  "eslint/no-compare-neg-zero": "error",
  "eslint/no-cond-assign": "error",
  "eslint/no-const-assign": "error",
  "eslint/no-constant-binary-expression": "error",
  "eslint/no-constant-condition": "error",
  "eslint/no-control-regex": "off",
  "eslint/no-debugger": "error",
  "eslint/no-delete-var": "warn",
  "eslint/no-dupe-class-members": "error",
  "eslint/no-dupe-else-if": "error",
  "eslint/no-dupe-keys": "error",
  "eslint/no-duplicate-case": "error",
  "eslint/no-empty-character-class": "error",
  "eslint/no-empty-pattern": "error",
  // "eslint/no-empty-static-block": "off",
  // "eslint/no-eval": "off",
  // "eslint/no-ex-assign": "off",
  // "eslint/no-extra-boolean-cast": "off",
  // "eslint/no-func-assign": "off",
  // "eslint/no-global-assign": "off",
  // "eslint/no-import-assign": "off",
  // "eslint/no-invalid-regexp": "off",
  // "eslint/no-irregular-whitespace": "off",
  // "eslint/no-iterator": "off",
  // "eslint/no-loss-of-precision": "off",
  // "eslint/no-misleading-character-class": "off",
  // "eslint/no-new-native-nonconstructor": "off",
  // "eslint/no-nonoctal-decimal-escape": "off",
  // "eslint/no-obj-calls": "off",
  // "eslint/no-self-assign": "off",
  // "eslint/no-setter-return": "off",
  // "eslint/no-shadow-restricted-names": "off",
  // "eslint/no-sparse-arrays": "off",
  // "eslint/no-this-before-super": "off",
  // "eslint/no-unassigned-vars": "off",
  // "eslint/no-unreachable": "off",
  // "eslint/no-unsafe-finally": "off",
  // "eslint/no-unsafe-negation": "off",
  // "eslint/no-unsafe-optional-chaining": "off",
  "eslint/no-unused-expressions": "error",
  "eslint/no-unused-labels": "error",
  "eslint/no-unused-private-class-members": "error",
  "eslint/no-unused-vars": "error",
  // "eslint/no-useless-backreference": "off",
  // "eslint/no-useless-catch": "off",
  // "eslint/no-useless-escape": "off",
  // "eslint/no-useless-rename": "off",
  // "eslint/no-with": "off",
  // "eslint/require-yield": "off",
  // "eslint/use-isnan": "off",
  // "eslint/valid-typeof": "off",
}

const nursery: DummyRuleMap = {
  // "eslint/no-restricted-exports": "off",
  // "eslint/no-undef": "off",
  // "eslint/no-useless-assignment": "off",
}

const pedantic: DummyRuleMap = {
  // "eslint/accessor-pairs": "off",
  // "eslint/array-callback-return": "off",
  // "eslint/eqeqeq": "off",
  // "eslint/max-classes-per-file": "off",
  // "eslint/max-depth": "off",
  // "eslint/max-lines": "off",
  // "eslint/max-lines-per-function": "off",
  // "eslint/max-nested-callbacks": "off",
  // "eslint/no-array-constructor": "off",
  // "eslint/no-case-declarations": "off",
  // "eslint/no-constructor-return": "off",
  // "eslint/no-else-return": "off",
  // "eslint/no-fallthrough": "off",
  // "eslint/no-inline-comments": "off",
  // "eslint/no-inner-declarations": "off",
  // "eslint/no-lonely-if": "off",
  // "eslint/no-loop-func": "off",
  // "eslint/no-negated-condition": "off",
  // "eslint/no-new-wrappers": "off",
  // "eslint/no-object-constructor": "off",
  // "eslint/no-promise-executor-return": "off",
  // "eslint/no-prototype-builtins": "off",
  // "eslint/no-redeclare": "off",
  // "eslint/no-self-compare": "off",
  // "eslint/no-throw-literal": "off",
  // "eslint/no-useless-return": "off",
  // "eslint/no-warning-comments": "off",
  // "eslint/radix": "off",
  // "eslint/require-await": "off",
  // "eslint/require-unicode-regexp": "off",
  // "eslint/sort-vars": "off",
  // "eslint/symbol-description": "off",
}

const perf: DummyRuleMap = {
  // "eslint/no-await-in-loop": "off",
  // "eslint/no-useless-call": "off",
}

const restriction: DummyRuleMap = {
  // "eslint/class-methods-use-this": "off",
  // "eslint/complexity": "off",
  // "eslint/default-case": "off",
  // "eslint/no-alert": "off",
  // "eslint/no-bitwise": "off",
  // "eslint/no-console": "off",
  // "eslint/no-div-regex": "off",
  // "eslint/no-empty": "off",
  // "eslint/no-empty-function": "off",
  // "eslint/no-eq-null": "off",
  // "eslint/no-implicit-globals": "off",
  // "eslint/no-param-reassign": "off",
  // "eslint/no-plusplus": "off",
  // "eslint/no-proto": "off",
  // "eslint/no-regex-spaces": "off",
  // "eslint/no-restricted-globals": "off",
  // "eslint/no-restricted-imports": "off",
  // "eslint/no-restricted-properties": "off",
  // "eslint/no-sequences": "off",
  // "eslint/no-undefined": "off",
  // "eslint/no-use-before-define": "off",
  // "eslint/no-var": "off",
  // "eslint/no-void": "off",
  // "eslint/unicode-bom": "off",
}

const style: DummyRuleMap = {
  // "eslint/arrow-body-style": "off",
  // "eslint/capitalized-comments": "off",
  // "eslint/curly": "off",
  // "eslint/default-case-last": "off",
  // "eslint/default-param-last": "off",
  // "eslint/func-name-matching": "off",
  // "eslint/func-names": "off",
  // "eslint/func-style": "off",
  // "eslint/grouped-accessor-pairs": "off",
  // "eslint/guard-for-in": "off",
  // "eslint/id-length": "off",
  // "eslint/id-match": "off",
  // "eslint/init-declarations": "off",
  // "eslint/logical-assignment-operators": "off",
  // "eslint/max-params": "off",
  // "eslint/max-statements": "off",
  // "eslint/new-cap": "off",
  // "eslint/no-continue": "off",
  // "eslint/no-duplicate-imports": "off",
  // "eslint/no-extra-label": "off",
  // "eslint/no-implicit-coercion": "off",
  // "eslint/no-label-var": "off",
  // "eslint/no-labels": "off",
  // "eslint/no-lone-blocks": "off",
  // "eslint/no-magic-numbers": "off",
  // "eslint/no-multi-assign": "off",
  // "eslint/no-multi-str": "off",
  // "eslint/no-nested-ternary": "off",
  // "eslint/no-new-func": "off",
  // "eslint/no-return-assign": "off",
  // "eslint/no-script-url": "off",
  // "eslint/no-template-curly-in-string": "off",
  // "eslint/no-ternary": "off",
  // "eslint/no-useless-computed-key": "off",
  // "eslint/object-shorthand": "off",
  // "eslint/operator-assignment": "off",
  // "eslint/prefer-arrow-callback": "off",
  // "eslint/prefer-const": "off",
  // "eslint/prefer-destructuring": "off",
  // "eslint/prefer-exponentiation-operator": "off",
  // "eslint/prefer-named-capture-group": "off",
  // "eslint/prefer-numeric-literals": "off",
  // "eslint/prefer-object-has-own": "off",
  // "eslint/prefer-object-spread": "off",
  // "eslint/prefer-promise-reject-errors": "off",
  // "eslint/prefer-regex-literals": "off",
  // "eslint/prefer-rest-params": "off",
  // "eslint/prefer-spread": "off",
  // "eslint/prefer-template": "off",
  // "eslint/sort-imports": "off",
  // "eslint/sort-keys": "off",
  // "eslint/vars-on-top": "off",
  // "eslint/yoda": "off",
}

const suspicious: DummyRuleMap = {
  // "eslint/block-scoped-var": "off",
  // "eslint/no-extend-native": "off",
  // "eslint/no-extra-bind": "off",
  // "eslint/no-implied-eval": "off",
  // "eslint/no-new": "off",
  // "eslint/no-shadow": "off",
  // "eslint/no-underscore-dangle": "off",
  // "eslint/no-unexpected-multiline": "off",
  // "eslint/no-unmodified-loop-condition": "off",
  // "eslint/no-unneeded-ternary": "off",
  // "eslint/no-useless-concat": "off",
  // "eslint/no-useless-constructor": "off",
  // "eslint/preserve-caught-error": "off",
}

export const eslintRules: DummyRuleMap = {
  ...correctness,
  ...nursery,
  ...pedantic,
  ...perf,
  ...restriction,
  ...style,
  ...suspicious,
}
