// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {BasicThemeData} from "./theme.types.js"

export const themeSpacing: Required<BasicThemeData>[] = [
  {tailwindClass: "*-qds-0", variable: "--spacing-0"},
  {tailwindClass: "*-qds-10", variable: "--spacing-10"},
  {tailwindClass: "*-qds-20", variable: "--spacing-20"},
  {tailwindClass: "*-qds-30", variable: "--spacing-30"},
  {tailwindClass: "*-qds-40", variable: "--spacing-40"},
  {tailwindClass: "*-qds-50", variable: "--spacing-50"},
  {tailwindClass: "*-qds-60", variable: "--spacing-60"},
  {tailwindClass: "*-qds-70", variable: "--spacing-70"},
  {tailwindClass: "*-qds-80", variable: "--spacing-80"},
  {tailwindClass: "*-qds-90", variable: "--spacing-90"},
  {tailwindClass: "*-qds-100", variable: "--spacing-100"},
  {tailwindClass: "*-qds-110", variable: "--spacing-110"},
  {tailwindClass: "*-qds-120", variable: "--spacing-120"},
  {tailwindClass: "*-qds-130", variable: "--spacing-130"},
  {tailwindClass: "*-qds-140", variable: "--spacing-140"},
  {tailwindClass: "*-qds-150", variable: "--spacing-150"},
  {tailwindClass: "*-qds-160", variable: "--spacing-160"},
  {tailwindClass: "*-qds-170", variable: "--spacing-170"},
  {tailwindClass: "*-qds-180", variable: "--spacing-180"},
  {tailwindClass: "*-qds-190", variable: "--spacing-190"},
  {tailwindClass: "*-qds-200", variable: "--spacing-200"},
  {tailwindClass: "*-qds-210", variable: "--spacing-210"},
  {tailwindClass: "*-qds-220", variable: "--spacing-220"},
  {tailwindClass: "*-qds-230", variable: "--spacing-230"},
  {tailwindClass: "*-qds-240", variable: "--spacing-240"},
  {tailwindClass: "*-qds-250", variable: "--spacing-250"},
  {tailwindClass: "*-qds-260", variable: "--spacing-260"},
  {tailwindClass: "*-qds-270", variable: "--spacing-270"},
  {tailwindClass: "*-qds-280", variable: "--spacing-280"},
  {tailwindClass: "*-qds-290", variable: "--spacing-290"},
  {tailwindClass: "*-qds-300", variable: "--spacing-300"},
  {tailwindClass: "*-qds-310", variable: "--spacing-310"},
  {tailwindClass: "*-qds-320", variable: "--spacing-320"},
  {tailwindClass: "*-qds-330", variable: "--spacing-330"},
]
